export function getDashboardHTML(): string {
  const html = [
    '<!DOCTYPE html>',
    '<html lang="en">',
    '<head>',
    '<meta charset="UTF-8">',
    '<title>OpenOcean Dashboard</title>',
    '<style>',
    '* { margin: 0; padding: 0; box-sizing: border-box; }',
    'body { font-family: system-ui, sans-serif; background: #0f1117; color: #e2e8f0; padding: 24px; }',
    'h1 { font-size: 24px; font-weight: 600; margin-bottom: 4px; }',
    '.subtitle { color: #64748b; font-size: 14px; margin-bottom: 32px; }',
    '.grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 16px; margin-bottom: 32px; }',
    '.card { background: #1e2130; border: 1px solid #2d3148; border-radius: 12px; padding: 20px; }',
    '.card-label { font-size: 12px; color: #64748b; text-transform: uppercase; margin-bottom: 8px; }',
    '.card-value { font-size: 32px; font-weight: 700; color: #7c6af7; }',
    '.card-sub { font-size: 12px; color: #64748b; margin-top: 4px; }',
    '.section { margin-bottom: 32px; }',
    '.section-title { font-size: 16px; font-weight: 600; margin-bottom: 16px; color: #94a3b8; }',
    'table { width: 100%; border-collapse: collapse; }',
    'th { text-align: left; font-size: 12px; color: #64748b; padding: 8px 12px; border-bottom: 1px solid #2d3148; }',
    'td { padding: 10px 12px; border-bottom: 1px solid #1a1f2e; font-size: 14px; }',
    '.badge { display: inline-block; padding: 2px 8px; border-radius: 999px; font-size: 11px; }',
    '.badge-telegram { background: #1a3a5c; color: #60a5fa; }',
    '.badge-discord { background: #1e1a3a; color: #818cf8; }',
    '.badge-websocket { background: #1a3a2a; color: #34d399; }',
    '.bar-wrap { background: #1e2130; border-radius: 4px; height: 8px; margin-top: 6px; }',
    '.bar { background: #7c6af7; height: 8px; border-radius: 4px; }',
    '.week-grid { display: grid; grid-template-columns: repeat(7, 1fr); gap: 8px; }',
    '.day-card { background: #1e2130; border: 1px solid #2d3148; border-radius: 8px; padding: 12px; text-align: center; }',
    '.day-date { font-size: 11px; color: #64748b; margin-bottom: 6px; }',
    '.day-msgs { font-size: 20px; font-weight: 700; color: #7c6af7; }',
    '.day-tokens { font-size: 11px; color: #64748b; margin-top: 2px; }',
    '.online { display: inline-block; width: 8px; height: 8px; background: #34d399; border-radius: 50%; margin-right: 6px; }',
    '.refresh { border: 1px solid #2d3148; background: none; color: #94a3b8; padding: 4px 12px; border-radius: 6px; cursor: pointer; }',
    '</style>',
    '</head>',
    '<body>',
    '<div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:4px">',
    '<h1><span class="online"></span>OpenOcean Dashboard</h1>',
    '<button class="refresh" onclick="loadAll()">Refresh</button>',
    '</div>',
    '<p class="subtitle">Real-time spend and session tracking</p>',
    '<div class="grid">',
    '<div class="card"><div class="card-label">Messages</div><div class="card-value" id="totalMessages">-</div><div class="card-sub">today</div></div>',
    '<div class="card"><div class="card-label">Tokens</div><div class="card-value" id="totalTokens">-</div><div class="card-sub">today</div></div>',
    '<div class="card"><div class="card-label">Cost</div><div class="card-value" id="totalCost">-</div><div class="card-sub">today</div></div>',
    '<div class="card"><div class="card-label">Model</div><div class="card-value" style="font-size:16px;margin-top:6px" id="activeModel">-</div><div class="card-sub">current</div></div>',
    '</div>',
    '<div class="section"><div class="section-title">This week</div><div class="week-grid" id="weekGrid"></div></div>',
    '<div class="section"><div class="section-title">By channel</div><div id="channelBars"></div></div>',
    '<div class="section"><div class="section-title">Recent messages</div>',
    '<table><thead><tr><th>Time</th><th>Channel</th><th>Model</th><th>Tokens</th><th>Cost</th></tr></thead>',
    '<tbody id="recentTable"></tbody></table></div>',
    '<script>',
    'async function loadSpend() {',
    '  const data = await fetch("/api/spend").then(r => r.json())',
    '  document.getElementById("totalMessages").textContent = data.totalMessages',
    '  document.getElementById("totalTokens").textContent = data.totalTokens.toLocaleString()',
    '  document.getElementById("totalCost").textContent = "$" + data.totalCost.toFixed(6)',
    '  document.getElementById("activeModel").textContent = data.recent[0]?.model ?? "mock"',
    '  const maxT = Math.max(...Object.values(data.byChannel).map(c => c.tokens), 1)',
    '  document.getElementById("channelBars").innerHTML = Object.entries(data.byChannel).map(([ch, d]) =>',
    '    "<div style=\'margin-bottom:12px\'>" +',
    '    "<div style=\'display:flex;justify-content:space-between;font-size:13px\'>" +',
    '    "<span class=\'badge badge-" + ch + "\'>" + ch + "</span>" +',
    '    "<span style=\'color:#64748b\'>" + d.messages + " msgs - " + d.tokens + " tokens</span></div>" +',
    '    "<div class=\'bar-wrap\'><div class=\'bar\' style=\'width:" + Math.round(d.tokens/maxT*100) + "%\'></div></div></div>"',
    '  ).join("") || "<p style=\'color:#64748b;font-size:14px\'>No messages yet today</p>"',
    '  document.getElementById("recentTable").innerHTML = data.recent.map(e =>',
    '    "<tr><td style=\'color:#64748b\'>" + new Date(e.timestamp).toLocaleTimeString() + "</td>" +',
    '    "<td><span class=\'badge badge-" + e.channel + "\'>" + e.channel + "</span></td>" +',
    '    "<td style=\'color:#94a3b8\'>" + e.model + "</td>" +',
    '    "<td>" + e.totalTokens + "</td>" +',
    '    "<td style=\'color:#34d399\'>$" + e.costUsd.toFixed(6) + "</td></tr>"',
    '  ).join("") || "<tr><td colspan=\'5\' style=\'color:#64748b;text-align:center;padding:24px\'>No messages yet</td></tr>"',
    '}',
    'async function loadWeek() {',
    '  const days = await fetch("/api/week").then(r => r.json())',
    '  const max = Math.max(...days.map(d => d.messages), 1)',
    '  document.getElementById("weekGrid").innerHTML = days.map(d =>',
    '    "<div class=\'day-card\'>" +',
    '    "<div class=\'day-date\'>" + d.date.slice(5) + "</div>" +',
    '    "<div class=\'day-msgs\'>" + d.messages + "</div>" +',
    '    "<div class=\'day-tokens\'>" + d.tokens + " tokens</div>" +',
    '    "<div class=\'bar-wrap\' style=\'margin-top:8px\'><div class=\'bar\' style=\'width:" + Math.round(d.messages/max*100) + "%\'></div></div>" +',
    '    "</div>"',
    '  ).join("")',
    '}',
    'async function loadAll() { await Promise.all([loadSpend(), loadWeek()]) }',
    'loadAll()',
    'setInterval(loadAll, 10000)',
    '</script>',
    '</body>',
    '</html>',
  ]
  return html.join('\n')
}